// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jupyterclient_test

import (
	"github.com/Theia-Scientific/jupyter-datasource/pkg/jupyterclient"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIJupyterHttpClient creates a new instance of MockIJupyterHttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJupyterHttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJupyterHttpClient {
	mock := &MockIJupyterHttpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIJupyterHttpClient is an autogenerated mock type for the IJupyterHttpClient type
type MockIJupyterHttpClient struct {
	mock.Mock
}

type MockIJupyterHttpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIJupyterHttpClient) EXPECT() *MockIJupyterHttpClient_Expecter {
	return &MockIJupyterHttpClient_Expecter{mock: &_m.Mock}
}

// CreateKernel provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) CreateKernel(kernelType string) (jupyterclient.KernelSpec, error) {
	ret := _mock.Called(kernelType)

	if len(ret) == 0 {
		panic("no return value specified for CreateKernel")
	}

	var r0 jupyterclient.KernelSpec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (jupyterclient.KernelSpec, error)); ok {
		return returnFunc(kernelType)
	}
	if returnFunc, ok := ret.Get(0).(func(string) jupyterclient.KernelSpec); ok {
		r0 = returnFunc(kernelType)
	} else {
		r0 = ret.Get(0).(jupyterclient.KernelSpec)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(kernelType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterHttpClient_CreateKernel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKernel'
type MockIJupyterHttpClient_CreateKernel_Call struct {
	*mock.Call
}

// CreateKernel is a helper method to define mock.On call
//   - kernelType string
func (_e *MockIJupyterHttpClient_Expecter) CreateKernel(kernelType interface{}) *MockIJupyterHttpClient_CreateKernel_Call {
	return &MockIJupyterHttpClient_CreateKernel_Call{Call: _e.mock.On("CreateKernel", kernelType)}
}

func (_c *MockIJupyterHttpClient_CreateKernel_Call) Run(run func(kernelType string)) *MockIJupyterHttpClient_CreateKernel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIJupyterHttpClient_CreateKernel_Call) Return(kernelSpec jupyterclient.KernelSpec, err error) *MockIJupyterHttpClient_CreateKernel_Call {
	_c.Call.Return(kernelSpec, err)
	return _c
}

func (_c *MockIJupyterHttpClient_CreateKernel_Call) RunAndReturn(run func(kernelType string) (jupyterclient.KernelSpec, error)) *MockIJupyterHttpClient_CreateKernel_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionInfo provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) GetConnectionInfo(id string) (jupyterclient.ConnectionInfo, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionInfo")
	}

	var r0 jupyterclient.ConnectionInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (jupyterclient.ConnectionInfo, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) jupyterclient.ConnectionInfo); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(jupyterclient.ConnectionInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterHttpClient_GetConnectionInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionInfo'
type MockIJupyterHttpClient_GetConnectionInfo_Call struct {
	*mock.Call
}

// GetConnectionInfo is a helper method to define mock.On call
//   - id string
func (_e *MockIJupyterHttpClient_Expecter) GetConnectionInfo(id interface{}) *MockIJupyterHttpClient_GetConnectionInfo_Call {
	return &MockIJupyterHttpClient_GetConnectionInfo_Call{Call: _e.mock.On("GetConnectionInfo", id)}
}

func (_c *MockIJupyterHttpClient_GetConnectionInfo_Call) Run(run func(id string)) *MockIJupyterHttpClient_GetConnectionInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIJupyterHttpClient_GetConnectionInfo_Call) Return(connectionInfo jupyterclient.ConnectionInfo, err error) *MockIJupyterHttpClient_GetConnectionInfo_Call {
	_c.Call.Return(connectionInfo, err)
	return _c
}

func (_c *MockIJupyterHttpClient_GetConnectionInfo_Call) RunAndReturn(run func(id string) (jupyterclient.ConnectionInfo, error)) *MockIJupyterHttpClient_GetConnectionInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetKernelSpecs provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) GetKernelSpecs() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKernelSpecs")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterHttpClient_GetKernelSpecs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKernelSpecs'
type MockIJupyterHttpClient_GetKernelSpecs_Call struct {
	*mock.Call
}

// GetKernelSpecs is a helper method to define mock.On call
func (_e *MockIJupyterHttpClient_Expecter) GetKernelSpecs() *MockIJupyterHttpClient_GetKernelSpecs_Call {
	return &MockIJupyterHttpClient_GetKernelSpecs_Call{Call: _e.mock.On("GetKernelSpecs")}
}

func (_c *MockIJupyterHttpClient_GetKernelSpecs_Call) Run(run func()) *MockIJupyterHttpClient_GetKernelSpecs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIJupyterHttpClient_GetKernelSpecs_Call) Return(bytes []byte, err error) *MockIJupyterHttpClient_GetKernelSpecs_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockIJupyterHttpClient_GetKernelSpecs_Call) RunAndReturn(run func() ([]byte, error)) *MockIJupyterHttpClient_GetKernelSpecs_Call {
	_c.Call.Return(run)
	return _c
}

// GetKernels provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) GetKernels() ([]jupyterclient.KernelSpec, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKernels")
	}

	var r0 []jupyterclient.KernelSpec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]jupyterclient.KernelSpec, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []jupyterclient.KernelSpec); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jupyterclient.KernelSpec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterHttpClient_GetKernels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKernels'
type MockIJupyterHttpClient_GetKernels_Call struct {
	*mock.Call
}

// GetKernels is a helper method to define mock.On call
func (_e *MockIJupyterHttpClient_Expecter) GetKernels() *MockIJupyterHttpClient_GetKernels_Call {
	return &MockIJupyterHttpClient_GetKernels_Call{Call: _e.mock.On("GetKernels")}
}

func (_c *MockIJupyterHttpClient_GetKernels_Call) Run(run func()) *MockIJupyterHttpClient_GetKernels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIJupyterHttpClient_GetKernels_Call) Return(kernelSpecs []jupyterclient.KernelSpec, err error) *MockIJupyterHttpClient_GetKernels_Call {
	_c.Call.Return(kernelSpecs, err)
	return _c
}

func (_c *MockIJupyterHttpClient_GetKernels_Call) RunAndReturn(run func() ([]jupyterclient.KernelSpec, error)) *MockIJupyterHttpClient_GetKernels_Call {
	_c.Call.Return(run)
	return _c
}

// GetListing provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) GetListing(path string) ([]jupyterclient.PathEntry, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetListing")
	}

	var r0 []jupyterclient.PathEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]jupyterclient.PathEntry, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []jupyterclient.PathEntry); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jupyterclient.PathEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterHttpClient_GetListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetListing'
type MockIJupyterHttpClient_GetListing_Call struct {
	*mock.Call
}

// GetListing is a helper method to define mock.On call
//   - path string
func (_e *MockIJupyterHttpClient_Expecter) GetListing(path interface{}) *MockIJupyterHttpClient_GetListing_Call {
	return &MockIJupyterHttpClient_GetListing_Call{Call: _e.mock.On("GetListing", path)}
}

func (_c *MockIJupyterHttpClient_GetListing_Call) Run(run func(path string)) *MockIJupyterHttpClient_GetListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIJupyterHttpClient_GetListing_Call) Return(pathEntrys []jupyterclient.PathEntry, err error) *MockIJupyterHttpClient_GetListing_Call {
	_c.Call.Return(pathEntrys, err)
	return _c
}

func (_c *MockIJupyterHttpClient_GetListing_Call) RunAndReturn(run func(path string) ([]jupyterclient.PathEntry, error)) *MockIJupyterHttpClient_GetListing_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotebook provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) GetNotebook(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetNotebook")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterHttpClient_GetNotebook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotebook'
type MockIJupyterHttpClient_GetNotebook_Call struct {
	*mock.Call
}

// GetNotebook is a helper method to define mock.On call
//   - path string
func (_e *MockIJupyterHttpClient_Expecter) GetNotebook(path interface{}) *MockIJupyterHttpClient_GetNotebook_Call {
	return &MockIJupyterHttpClient_GetNotebook_Call{Call: _e.mock.On("GetNotebook", path)}
}

func (_c *MockIJupyterHttpClient_GetNotebook_Call) Run(run func(path string)) *MockIJupyterHttpClient_GetNotebook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIJupyterHttpClient_GetNotebook_Call) Return(s string, err error) *MockIJupyterHttpClient_GetNotebook_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIJupyterHttpClient_GetNotebook_Call) RunAndReturn(run func(path string) (string, error)) *MockIJupyterHttpClient_GetNotebook_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotebooks provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) GetNotebooks() ([]jupyterclient.PathEntry, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNotebooks")
	}

	var r0 []jupyterclient.PathEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]jupyterclient.PathEntry, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []jupyterclient.PathEntry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jupyterclient.PathEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterHttpClient_GetNotebooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotebooks'
type MockIJupyterHttpClient_GetNotebooks_Call struct {
	*mock.Call
}

// GetNotebooks is a helper method to define mock.On call
func (_e *MockIJupyterHttpClient_Expecter) GetNotebooks() *MockIJupyterHttpClient_GetNotebooks_Call {
	return &MockIJupyterHttpClient_GetNotebooks_Call{Call: _e.mock.On("GetNotebooks")}
}

func (_c *MockIJupyterHttpClient_GetNotebooks_Call) Run(run func()) *MockIJupyterHttpClient_GetNotebooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIJupyterHttpClient_GetNotebooks_Call) Return(pathEntrys []jupyterclient.PathEntry, err error) *MockIJupyterHttpClient_GetNotebooks_Call {
	_c.Call.Return(pathEntrys, err)
	return _c
}

func (_c *MockIJupyterHttpClient_GetNotebooks_Call) RunAndReturn(run func() ([]jupyterclient.PathEntry, error)) *MockIJupyterHttpClient_GetNotebooks_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessions provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) GetSessions() ([]jupyterclient.Session, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSessions")
	}

	var r0 []jupyterclient.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]jupyterclient.Session, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []jupyterclient.Session); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jupyterclient.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterHttpClient_GetSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessions'
type MockIJupyterHttpClient_GetSessions_Call struct {
	*mock.Call
}

// GetSessions is a helper method to define mock.On call
func (_e *MockIJupyterHttpClient_Expecter) GetSessions() *MockIJupyterHttpClient_GetSessions_Call {
	return &MockIJupyterHttpClient_GetSessions_Call{Call: _e.mock.On("GetSessions")}
}

func (_c *MockIJupyterHttpClient_GetSessions_Call) Run(run func()) *MockIJupyterHttpClient_GetSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIJupyterHttpClient_GetSessions_Call) Return(sessions []jupyterclient.Session, err error) *MockIJupyterHttpClient_GetSessions_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *MockIJupyterHttpClient_GetSessions_Call) RunAndReturn(run func() ([]jupyterclient.Session, error)) *MockIJupyterHttpClient_GetSessions_Call {
	_c.Call.Return(run)
	return _c
}

// KillKernel provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) KillKernel(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for KillKernel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIJupyterHttpClient_KillKernel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillKernel'
type MockIJupyterHttpClient_KillKernel_Call struct {
	*mock.Call
}

// KillKernel is a helper method to define mock.On call
//   - id string
func (_e *MockIJupyterHttpClient_Expecter) KillKernel(id interface{}) *MockIJupyterHttpClient_KillKernel_Call {
	return &MockIJupyterHttpClient_KillKernel_Call{Call: _e.mock.On("KillKernel", id)}
}

func (_c *MockIJupyterHttpClient_KillKernel_Call) Run(run func(id string)) *MockIJupyterHttpClient_KillKernel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIJupyterHttpClient_KillKernel_Call) Return(err error) *MockIJupyterHttpClient_KillKernel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIJupyterHttpClient_KillKernel_Call) RunAndReturn(run func(id string) error) *MockIJupyterHttpClient_KillKernel_Call {
	_c.Call.Return(run)
	return _c
}

// Restart provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) Restart(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIJupyterHttpClient_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type MockIJupyterHttpClient_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - id string
func (_e *MockIJupyterHttpClient_Expecter) Restart(id interface{}) *MockIJupyterHttpClient_Restart_Call {
	return &MockIJupyterHttpClient_Restart_Call{Call: _e.mock.On("Restart", id)}
}

func (_c *MockIJupyterHttpClient_Restart_Call) Run(run func(id string)) *MockIJupyterHttpClient_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIJupyterHttpClient_Restart_Call) Return(err error) *MockIJupyterHttpClient_Restart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIJupyterHttpClient_Restart_Call) RunAndReturn(run func(id string) error) *MockIJupyterHttpClient_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// SelectKernel provides a mock function for the type MockIJupyterHttpClient
func (_mock *MockIJupyterHttpClient) SelectKernel() (jupyterclient.KernelSpec, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SelectKernel")
	}

	var r0 jupyterclient.KernelSpec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (jupyterclient.KernelSpec, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() jupyterclient.KernelSpec); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(jupyterclient.KernelSpec)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterHttpClient_SelectKernel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectKernel'
type MockIJupyterHttpClient_SelectKernel_Call struct {
	*mock.Call
}

// SelectKernel is a helper method to define mock.On call
func (_e *MockIJupyterHttpClient_Expecter) SelectKernel() *MockIJupyterHttpClient_SelectKernel_Call {
	return &MockIJupyterHttpClient_SelectKernel_Call{Call: _e.mock.On("SelectKernel")}
}

func (_c *MockIJupyterHttpClient_SelectKernel_Call) Run(run func()) *MockIJupyterHttpClient_SelectKernel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIJupyterHttpClient_SelectKernel_Call) Return(kernelSpec jupyterclient.KernelSpec, err error) *MockIJupyterHttpClient_SelectKernel_Call {
	_c.Call.Return(kernelSpec, err)
	return _c
}

func (_c *MockIJupyterHttpClient_SelectKernel_Call) RunAndReturn(run func() (jupyterclient.KernelSpec, error)) *MockIJupyterHttpClient_SelectKernel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIJupyterSession creates a new instance of MockIJupyterSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJupyterSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJupyterSession {
	mock := &MockIJupyterSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIJupyterSession is an autogenerated mock type for the IJupyterSession type
type MockIJupyterSession struct {
	mock.Mock
}

type MockIJupyterSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIJupyterSession) EXPECT() *MockIJupyterSession_Expecter {
	return &MockIJupyterSession_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockIJupyterSession
func (_mock *MockIJupyterSession) Execute(code string) (jupyterclient.Result, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 jupyterclient.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (jupyterclient.Result, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) jupyterclient.Result); ok {
		r0 = returnFunc(code)
	} else {
		r0 = ret.Get(0).(jupyterclient.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterSession_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockIJupyterSession_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - code string
func (_e *MockIJupyterSession_Expecter) Execute(code interface{}) *MockIJupyterSession_Execute_Call {
	return &MockIJupyterSession_Execute_Call{Call: _e.mock.On("Execute", code)}
}

func (_c *MockIJupyterSession_Execute_Call) Run(run func(code string)) *MockIJupyterSession_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIJupyterSession_Execute_Call) Return(result jupyterclient.Result, err error) *MockIJupyterSession_Execute_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockIJupyterSession_Execute_Call) RunAndReturn(run func(code string) (jupyterclient.Result, error)) *MockIJupyterSession_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Initialize provides a mock function for the type MockIJupyterSession
func (_mock *MockIJupyterSession) Initialize(packages *[]string, code string) error {
	ret := _mock.Called(packages, code)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*[]string, string) error); ok {
		r0 = returnFunc(packages, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIJupyterSession_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockIJupyterSession_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - packages *[]string
//   - code string
func (_e *MockIJupyterSession_Expecter) Initialize(packages interface{}, code interface{}) *MockIJupyterSession_Initialize_Call {
	return &MockIJupyterSession_Initialize_Call{Call: _e.mock.On("Initialize", packages, code)}
}

func (_c *MockIJupyterSession_Initialize_Call) Run(run func(packages *[]string, code string)) *MockIJupyterSession_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *[]string
		if args[0] != nil {
			arg0 = args[0].(*[]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIJupyterSession_Initialize_Call) Return(err error) *MockIJupyterSession_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIJupyterSession_Initialize_Call) RunAndReturn(run func(packages *[]string, code string) error) *MockIJupyterSession_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockIJupyterSession
func (_mock *MockIJupyterSession) Query(code string) (jupyterclient.Result, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 jupyterclient.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (jupyterclient.Result, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) jupyterclient.Result); ok {
		r0 = returnFunc(code)
	} else {
		r0 = ret.Get(0).(jupyterclient.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterSession_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockIJupyterSession_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - code string
func (_e *MockIJupyterSession_Expecter) Query(code interface{}) *MockIJupyterSession_Query_Call {
	return &MockIJupyterSession_Query_Call{Call: _e.mock.On("Query", code)}
}

func (_c *MockIJupyterSession_Query_Call) Run(run func(code string)) *MockIJupyterSession_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIJupyterSession_Query_Call) Return(result jupyterclient.Result, err error) *MockIJupyterSession_Query_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockIJupyterSession_Query_Call) RunAndReturn(run func(code string) (jupyterclient.Result, error)) *MockIJupyterSession_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Quit provides a mock function for the type MockIJupyterSession
func (_mock *MockIJupyterSession) Quit() {
	_mock.Called()
	return
}

// MockIJupyterSession_Quit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Quit'
type MockIJupyterSession_Quit_Call struct {
	*mock.Call
}

// Quit is a helper method to define mock.On call
func (_e *MockIJupyterSession_Expecter) Quit() *MockIJupyterSession_Quit_Call {
	return &MockIJupyterSession_Quit_Call{Call: _e.mock.On("Quit")}
}

func (_c *MockIJupyterSession_Quit_Call) Run(run func()) *MockIJupyterSession_Quit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIJupyterSession_Quit_Call) Return() *MockIJupyterSession_Quit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIJupyterSession_Quit_Call) RunAndReturn(run func()) *MockIJupyterSession_Quit_Call {
	_c.Run(run)
	return _c
}

// Restart provides a mock function for the type MockIJupyterSession
func (_mock *MockIJupyterSession) Restart() {
	_mock.Called()
	return
}

// MockIJupyterSession_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type MockIJupyterSession_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
func (_e *MockIJupyterSession_Expecter) Restart() *MockIJupyterSession_Restart_Call {
	return &MockIJupyterSession_Restart_Call{Call: _e.mock.On("Restart")}
}

func (_c *MockIJupyterSession_Restart_Call) Run(run func()) *MockIJupyterSession_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIJupyterSession_Restart_Call) Return() *MockIJupyterSession_Restart_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIJupyterSession_Restart_Call) RunAndReturn(run func()) *MockIJupyterSession_Restart_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockIJupyterSession
func (_mock *MockIJupyterSession) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIJupyterSession_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockIJupyterSession_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockIJupyterSession_Expecter) Start() *MockIJupyterSession_Start_Call {
	return &MockIJupyterSession_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockIJupyterSession_Start_Call) Run(run func()) *MockIJupyterSession_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIJupyterSession_Start_Call) Return(err error) *MockIJupyterSession_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIJupyterSession_Start_Call) RunAndReturn(run func() error) *MockIJupyterSession_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Log provides a mock function for the type MockLogger
func (_mock *MockLogger) Log(s string) {
	_mock.Called(s)
	return
}

// MockLogger_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockLogger_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - s string
func (_e *MockLogger_Expecter) Log(s interface{}) *MockLogger_Log_Call {
	return &MockLogger_Log_Call{Call: _e.mock.On("Log", s)}
}

func (_c *MockLogger_Log_Call) Run(run func(s string)) *MockLogger_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_Log_Call) Return() *MockLogger_Log_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Log_Call) RunAndReturn(run func(s string)) *MockLogger_Log_Call {
	_c.Run(run)
	return _c
}
