services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    network_mode: host
    env_file: .env
    environment:
      GF_FEATURE_TOGGLES_ENABLE: localizationForPlugins
