services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    network_mode: host
    env_file: .env
    environment:
      GF_FEATURE_TOGGLES_ENABLE: localizationForPlugins

  jupyter:
    container_name: jupyter
    depends_on:
      - system
    env_file: .env
    image: ghcr.io/theia-scientific/theia-jupyter:latest
    network_mode: host
    privileged: true

  nginx:
    container_name: nginx
    depends_on:
      - grafana
      - system
    env_file: .env
    image: ghcr.io/theia-scientific/theia-nginx:latest
    network_mode: host
    privileged: true

  postgres:
    container_name: postgres
    depends_on:
      - system
    env_file: .env
    image: ghcr.io/theia-scientific/theia-postgres:latest
    network_mode: host
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
      - /sys:/sys
      - /proc:/proc

  system:
    container_name: system
    env_file: .env
    image: ghcr.io/theia-scientific/theia-system:latest
    network_mode: host
    privileged: true
    volumes:
      - /run/dbus/system_bus_socket:/host/run/dbus/system_bus_socket
