import { createSelector } from '@volkovlabs/jest-selectors';

/**
 * Tests Identifiers
 */
export const TEST_IDS = {
  config: {
    buttonUpdate: 'data-testid config button-update',
    root: 'data-testid config',
  },
  home: {
    root: 'data-testid root-page',
  },
  filesList: {
    buttonAddCategory: 'data-testid files-list button-add-category',
    buttonAddFile: 'data-testid files-list button-add-file',
    buttonAddRootCategory: 'data-testid files-list button-add-root-category',
    buttonAddRootFile: 'data-testid files-list button-add-root-file',
    buttonCancelAddCategory: 'data-testid files-list button-cancel-add-category',
    buttonCancelAddFile: 'data-testid files-list button-cancel-add-file',
    buttonCancelMoving: 'data-testid files-list button-cancel-moving',
    buttonCategoryCancelEdit: 'data-testid files-list button-category-cancel-edit',
    buttonCategorySaveEdit: 'data-testid files-list button-category-save-edit',
    buttonCategoryStartEdit: 'data-testid files-list button-category-start-edit',
    buttonCollapse: 'data-testid files-list button-collapse',
    buttonDownload: 'data-testid files-list button-download',
    buttonExpand: 'data-testid files-list button-expand',
    buttonFileCancelEdit: 'data-testid files-list button-file-cancel-edit',
    buttonFilePlay: 'data-testid files-list button-file-play',
    buttonFileSaveEdit: 'data-testid files-list button-file-save-edit',
    buttonFileStartEdit: 'data-testid files-list button-file-start-edit',
    buttonRefresh: 'data-testid files-list button-refresh',
    buttonSaveAddCategory: 'data-testid files-list button-save-add-category',
    buttonSaveMoving: 'data-testid files-list button-save-moving',
    buttonStartMoving: 'data-testid files-list button-start-moving',
    buttonStartRemoving: 'data-testid files-list button-start-removing',
    buttonToggleSearching: 'data-testid files-list button-toggle-searching',
    category: (path: unknown) => `data-testid files-list category-${path}`,
    categoryContent: (path: unknown) => `data-testid files-list category-content-${path}`,
    confirmDeleteModal: 'data-testid files-list confirm-delete-modal',
    confirmItemDeleteModal: 'data-testid files-list confirm-item-delete-modal',
    errorMessage: 'data-testid files-list error-message',
    fieldCategoryName: 'data-testid files-list field-category-name',
    fieldFileName: 'data-testid files-list field-file-name',
    fieldMoveToPath: 'files-list field-move-to-path',
    fieldNewCategoryName: 'data-testid files-list field-new-category-name',
    fieldNewFile: 'data-testid files-list field-new-file',
    fieldSearch: 'data-testid files-list field-search',
    fieldSort: 'files-list field-sort',
    file: (path: unknown) => `data-testid files-list file-${path}`,
    fileName: (path: unknown) => `files-list file-name-${path}`,
    itemCheckbox: (path: unknown) => `data-testid files-list item-checkbox-${path}`,
    modalMoving: 'data-testid files-list modal-moving',
    noFilesMessage: 'data-testid files-list no-files-message',
    root: 'data-testid files-list',
    tree: (path: unknown) => `data-testid files-list tree-${path}`,
    buttonDeleteFile: 'data-testid files-list button-delete-file',
    buttonDeleteCategory: 'data-testid files-list button-delete-category',
    toggleAnalyzeOnUpload: 'data-testid files-list switch-analyze-on-upload'
  },
  colorPicker: {
    buttonSetRandom: 'data-testid color-picker button-set-random',
    buttonSelectColor: 'data-testid color-picker button-select-color',
    colorSwatch: 'data-testid color-picker color-swatch',
  },
  classColorsEditor: {
    root: 'data-testid class-colors-editor',
    item: (id: unknown) => `data-testid class-colors-editor item-${id}`,
    fieldName: 'data-testid class-colors-editor item field-name',
    fieldColor: 'data-testid class-colors-editor item field-color',
    buttonDelete: 'data-testid class-colors-editor item button-delete',
    buttonAdd: 'data-testid class-colors-editor item button-add',
  },
  modelConfiguration: {
    actor: 'data-testid model-configuration actor',
    buttonUpdate: 'data-testid model-configuration button-update',
    buttonSave: 'data-testid model-configuration button-save',
    buttonClose: 'data-testid model-configuration button-close',
    buttonDownload: 'data-testid model-configuration button-download',
    cuda: 'data-testid model-configuration cuda',
    distributed: 'data-testid model-configuration distributed',
    fieldDescription: 'data-testid model-configuration field-description',
    fieldTitle: 'data-testid model-configuration field-title',
    noActorMessage: 'data-testid model-configuration no-actor-message',
    noGPUMessage: 'data-testid model-configuration no-gpu-message',
    trackingParameters: 'data-testid model-configuration tracking-parameters',
    tilingParameters: 'data-testid model-configuration tiling-parameters',
  },
  modelCustomParametersEditor: {
    item: (value: unknown) => `data-testid model-custom-parameters-editor item-${value}`,
    fieldItemName: 'data-testid model-custom-parameters-editor field-item-name',
    fieldItemValue: 'data-testid model-custom-parameters-editor field-item-value',
    buttonDelete: 'data-testid model-custom-parameters-editor button-delete',
    buttonAdd: 'data-testid model-custom-parameters-editor button-add',
  },
  dateTimeFilter: {
    buttonRemove: createSelector('data-testid date-time-filter button-remove'),
    buttonSet: createSelector('data-testid date-time-filter button-set'),
  },
  fovEditor: {
    fieldPosition: createSelector('data-testid fov-editor field-position'),
    fieldWidth: createSelector('data-testid fov-editor field-fov-width'),
    fieldHeight: createSelector('data-testid fov-editor field-fov-height'),
    positionOption: createSelector((name: unknown) => `fov-editor position-option-${name}`),
  },
  stringArrayEditor: {
    item: createSelector((index: unknown) => `data-testid string-array-editor item-${index}`),
    buttonItemDelete: createSelector((index: unknown) => `data-testid string-array-editor item-${index} button-delete`),
    fieldItemValue: createSelector((index: unknown) => `data-testid string-array-editor item-${index} field-value`),
    buttonAdd: createSelector('data-testid string-array-editor button-add'),
  },
};
