// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package plugin_test

import (
	"context"

	"github.com/Theia-Scientific/jupyter-datasource/pkg/jupyterclient"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIJupyterSessionFactory creates a new instance of MockIJupyterSessionFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIJupyterSessionFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIJupyterSessionFactory {
	mock := &MockIJupyterSessionFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIJupyterSessionFactory is an autogenerated mock type for the IJupyterSessionFactory type
type MockIJupyterSessionFactory struct {
	mock.Mock
}

type MockIJupyterSessionFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIJupyterSessionFactory) EXPECT() *MockIJupyterSessionFactory_Expecter {
	return &MockIJupyterSessionFactory_Expecter{mock: &_m.Mock}
}

// MakeJupyterSession provides a mock function for the type MockIJupyterSessionFactory
func (_mock *MockIJupyterSessionFactory) MakeJupyterSession(ctx context.Context, ci *jupyterclient.ConnectionInfo, logger jupyterclient.Logger) (jupyterclient.IJupyterSession, error) {
	ret := _mock.Called(ctx, ci, logger)

	if len(ret) == 0 {
		panic("no return value specified for MakeJupyterSession")
	}

	var r0 jupyterclient.IJupyterSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *jupyterclient.ConnectionInfo, jupyterclient.Logger) (jupyterclient.IJupyterSession, error)); ok {
		return returnFunc(ctx, ci, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *jupyterclient.ConnectionInfo, jupyterclient.Logger) jupyterclient.IJupyterSession); ok {
		r0 = returnFunc(ctx, ci, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jupyterclient.IJupyterSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *jupyterclient.ConnectionInfo, jupyterclient.Logger) error); ok {
		r1 = returnFunc(ctx, ci, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIJupyterSessionFactory_MakeJupyterSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeJupyterSession'
type MockIJupyterSessionFactory_MakeJupyterSession_Call struct {
	*mock.Call
}

// MakeJupyterSession is a helper method to define mock.On call
//   - ctx context.Context
//   - ci *jupyterclient.ConnectionInfo
//   - logger jupyterclient.Logger
func (_e *MockIJupyterSessionFactory_Expecter) MakeJupyterSession(ctx interface{}, ci interface{}, logger interface{}) *MockIJupyterSessionFactory_MakeJupyterSession_Call {
	return &MockIJupyterSessionFactory_MakeJupyterSession_Call{Call: _e.mock.On("MakeJupyterSession", ctx, ci, logger)}
}

func (_c *MockIJupyterSessionFactory_MakeJupyterSession_Call) Run(run func(ctx context.Context, ci *jupyterclient.ConnectionInfo, logger jupyterclient.Logger)) *MockIJupyterSessionFactory_MakeJupyterSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *jupyterclient.ConnectionInfo
		if args[1] != nil {
			arg1 = args[1].(*jupyterclient.ConnectionInfo)
		}
		var arg2 jupyterclient.Logger
		if args[2] != nil {
			arg2 = args[2].(jupyterclient.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIJupyterSessionFactory_MakeJupyterSession_Call) Return(iJupyterSession jupyterclient.IJupyterSession, err error) *MockIJupyterSessionFactory_MakeJupyterSession_Call {
	_c.Call.Return(iJupyterSession, err)
	return _c
}

func (_c *MockIJupyterSessionFactory_MakeJupyterSession_Call) RunAndReturn(run func(ctx context.Context, ci *jupyterclient.ConnectionInfo, logger jupyterclient.Logger) (jupyterclient.IJupyterSession, error)) *MockIJupyterSessionFactory_MakeJupyterSession_Call {
	_c.Call.Return(run)
	return _c
}
